version: '3'
services:
  productservice:
    container_name: product-app
    image: kkatleri/productservice
    restart: on-failure
    ports:
      - 10586:8086
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
      - couponservice

  couponservice:
    container_name: coupon-app
    image: kkatleri/couponservice
    restart: on-failure
    ports:
      - 10585:8085
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
    
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: product_coupons
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 6666:3306
    healthcheck:
      test: "/user/bin/mysql --user=root --password=mysql --execute \"SHOW DATABASES\""
      interval: 4s
      timeout: 20s
      retries: 5