apiVersion: v1
kind: Service
metadata:
  name: coupon-app
  labels:
    app: coupon-app
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30285
  selector:
    app: coupon-app