apiVersion: v1
kind: Service
metadata:
  name: product-app
  labels:
    app: product-app
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30286
  selector:
    app: product-app